#---------------------------------#
#      General Configuration      #
#---------------------------------#

# Version format.
version: 1.0.{build}

# Branches to build.
branches:
  only:
    - master

# Do not build on tags (GitHub only).
skip_tags: true

#---------------------------------#
#    Environment Configuration    #
#---------------------------------#

# Operating system (build VM template).
os: Windows Server 2016

# Scripts that are called at very beginning, before repo cloning.
init:
  - git config --global core.autocrlf input

# Do not fetch the repository as a zip archive.
shallow_clone: false

# Build cache to preserve between builds.
cache:
  - NuGet -> csharp\packages\

# Scripts that run after cloning repository.
install:
  # Move to the C# directory and restore NuGet packages.
  - echo %CD%
  - ps: cd csharp
  - echo %CD%
  - ps: nuget restore

# Enable patching of the Assembly Info file.
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# Disable registration of private AppVeyor NuGet feeds.
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

#---------------------------------#
#       Build Configuration       #
#---------------------------------#

# Build platform, i.e. x86, x64, Any CPU.
platform: Any CPU

# Build configuration.
configuration:
  - Release

build:
  parallel: false
  verbosity: normal

# Scripts to run before build.
before_build:
  - echo %CD%
  - ps: cd ..
  - ps: ls
  - echo %CD%
