concurrency:
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    group: ${{ github.workflow }}-${{ github.ref }}

env:
    CI: 1

jobs:
    build:
        if: github.actor != 'dependabot[bot]'
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

            - name: Install pnpm
              uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb
              with:
                  version: latest

            - name: Setup Node
              uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
              with:
                  node-version-file: .nvmrc

            - id: pnpm-store
              name: Get pnpm store path
              run: echo "path=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Cache pnpm store
              uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
              with:
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-store.outputs.path }}
                  restore-keys: ${{ runner.os }}-pnpm-

            # https://docs.astral.sh/uv/guides/integration/github/
            - name: Install uv
              uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
              with:
                  enable-cache: true

            # https://just.systems/man/en/github-actions.html
            - name: Install Just
              uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3

            - name: Cache Cargo
              uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
              with:
                  key: ${{ runner.os }}-cargo-${{ hashFiles('rust/Cargo.lock') }}
                  path: |
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      rust/target/
                  restore-keys: ${{ runner.os }}-cargo-

            - name: Cache NuGet
              uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
              with:
                  key: ${{ runner.os }}-nuget-${{ hashFiles('csharp/**/*.csproj') }}
                  path: ~/.nuget/packages
                  restore-keys: ${{ runner.os }}-nuget-

            - if: runner.os == 'Linux'
              name: Install Linux libraries
              run: sudo apt-get install -y cpanminus

            - if: runner.os == 'macOS'
              name: Install MacOS libraries
              run: brew install clang-format cpanminus

            - name: Install dependencies
              run: just install

            - name: Spellcheck
              run: just spellcheck

            - name: JavaScript tests
              run: just javascript

            - name: Python tests
              run: just python

            - name: C++ tests
              run: just cpp

            - name: Perl tests
              run: just perl

            - name: Rust tests
              run: just rust

            - name: C# tests
              run: just csharp

        strategy:
            fail-fast: false
            matrix:
                os:
                    - macos-15
                    - ubuntu-24.04

name: build

on:
    pull_request:
    push:
        branches:
            - main
    workflow_dispatch:
